name: meteo_repository
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities
  intl: ^0.20.2
  http: ^1.3.0
  logger: ^2.5.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true